### ISSUE TITLE
Statamic v2 support

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [mike-zarandona/Statamic-LeadingZeros#1]
This doesnt seem to work with Statamic v2, is there any plan to support it?

**Comment by matthewjumpsoffbuildings** [comment]
This works: 

```php 
<?php

namespace Statamic\Addons\LeadingZeros;

use Statamic\Extend\Modifier;

class LeadingZerosModifier extends Modifier
{
    /**
     * Modify a value
     *
     * @param mixed  $value    The value to be modified
     * @param array  $params   Any parameters used in the modifier
     * @param array  $context  Contextual values
     * @return mixed
     */
    public function index($value, $params, $context)
    {
		if ( strlen($value) >= $params[0] ) {
            return $value;
        }
        else {
            $numLoops = $params[0] - strlen($value);

            for ( $i = 0; $i < $numLoops; $i++ ) {
                $value = '0' . $value;
            }

            return $value;
        }
    }
}

**Comment by mike-zarandona** [comment]
Hey @matthewjumpsoffbuildings - there are currently no plans to migrate this package to Statamic v2 since my team has opted to use a different CMS for new projects.

**Comment by matthewjumpsoffbuildings** [comment]
hey @mike-zarandona thanks for getting back to me, just out of curiosity which CMS have you switched to?

**Comment by mike-zarandona** [comment]
We've decided to go with CraftCMS since it shares a lot of the concepts from Statamic, but gives us more fine-grain control, more frequent updates, and less time coding up backend templates.  Just have to get used to having a DB again.
